# fly.toml app configuration file generated for apollo-mockup-backend on 2023-08-22T23:25:11-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "apollo-mockup-backend"
primary_region = "lax"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
